title: "Bashir Kabir |"
description: "My thoughts on Hacking, Cybersecurity And AI"
baseurl: ""
url: "https://L0C4LH057.github.io"
author: "Bashir Kabir Zarewa"

theme: minima
plugins:
  - jekyll-feed

collections:
  top_posts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post